# Generated by Django 3.1.7 on 2021-03-11 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminlte3', '0002_classes_studentsinclass'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZoomMeeting',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('meetingStart', models.DateTimeField()),
                ('meetingEnd', models.DateTimeField()),
                ('classId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminlte3.classes')),
            ],
        ),
    ]
